import React from 'react';

const AIAssistantFeatures = () => {
  const features = [
    {
      id: 1,
      title: "AI-Powered Assistance",
      description: "Nerdy Buddy understands natural language, allowing employees to ask questions just like they would with a real colleague. From HR policies to technical SOPs, it provides instant, accurate, and contextual answers tailored to the organization's knowledge base.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/ai-assistance-263x304.png",
      alt: "ai assistance"
    },
    {
      id: 2,
      title: "Secure Document Access",
      description: "Security is a top priority. Only vectorized, indexed data is shared with the AI engine. Your original documents stay safely stored on your servers, ensuring compliance and minimizing data exposure risks.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/secure-doucment-acess-263x304.png",
      alt: "secure document access"
    },
    {
      id: 3,
      title: "Real-Time Analytics & Feedback",
      description: "Get actionable insights with detailed usage reports. Identify the most asked questions, detect knowledge gaps, track training performance, and gather employee feedback, all in one intuitive dashboard.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/Real-time-analytics-263x304.png",
      alt: "Real time analytics"
    },
    {
      id: 4,
      title: "Simplified Onboarding",
      description: "New hire orientation is now automated. Nerdy Buddy walks fresh employees through customized onboarding workflows, covering company culture, tools, key policies, and role-specific training, saving HR time and ensuring consistency.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/8-263x304.png",
      alt: "8"
    },
    {
      id: 5,
      title: "AI-Generated Training & Quizzes",
      description: "Every month, department-specific quizzes are automatically generated by Nerdy Buddy. This keeps employees engaged, reinforces learning, and helps track individual progress through fun, bite-sized training modules.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/ai-genrated-training-263x304.png",
      alt: "ai generated training"
    },
    {
      id: 6,
      title: "Anti-Plagiarism Controls",
      description: "Protect your proprietary knowledge. The system can detect and block unauthorized copying, screen sharing, or external sharing of sensitive training material, maintaining the integrity of internal content.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/anti-plagiarism-263x304.png",
      alt: "anti plagiarism"
    },
    {
      id: 7,
      title: "Interactive Experience",
      description: "Make it personal! Nerdy Buddy includes a customizable character that reflects your organization's identity, complete with region-specific attire and animated expressions for a friendly, localized interaction experience.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/intrective-experience-263x304.png",
      alt: "interactive experience"
    },
    {
      id: 8,
      title: "Universal Availability",
      description: "Whether in the office or on the move, Nerdy Buddy is available across web browsers, mobile devices, and even kiosk stations. Facial recognition ensures secure logins for sensitive workflows.",
      image: "https://nerdybuddy.com/wp-content/uploads/2025/05/universal-avability-263x304.png",
      alt: "universal availability"
    }
  ];

  const ArrowIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="currentColor">
      <path d="M5.83333 15C5.58333 15 5.41667 14.9167 5.25 14.75C4.91667 14.4167 4.91667 13.9167 5.25 13.5833L13.5833 5.25C13.9167 4.91667 14.4167 4.91667 14.75 5.25C15.0833 5.58333 15.0833 6.08333 14.75 6.41667L6.41667 14.75C6.25 14.9167 6.08333 15 5.83333 15Z" />
      <path d="M14.1664 14.1667C13.6664 14.1667 13.3331 13.8333 13.3331 13.3333V6.66667H6.6664C6.1664 6.66667 5.83307 6.33333 5.83307 5.83333C5.83307 5.33333 6.1664 5 6.6664 5H14.1664C14.6664 5 14.9997 5.33333 14.9997 5.83333V13.3333C14.9997 13.8333 14.6664 14.1667 14.1664 14.1667Z" />
    </svg>
  );

  return (
    <section className="relative w-full min-h-screen bg-white overflow-hidden">
      {/* Background image section */}
      <div className="absolute top-0 left-0 w-full h-full">
        <img
          src="https://nerdybuddy.com/wp-content/uploads/2025/05/12345.png"
          alt="Background pattern"
          className="w-full h-full object-cover opacity-5 sm:opacity-10"
        />
      </div>

      {/* Robot image - Hidden on mobile/tablet */}
      <div className="absolute left-1/4 top-1/4 z-10 hidden xl:block">
        <img
          src="https://nerdybuddy.com/wp-content/uploads/2024/11/robot-ss4-h4.webp"
          alt="AI Assistant Robot"
          className="w-40 xl:w-48 h-auto"
        />
      </div>

      <div className="container mx-auto px-4 sm:px-6 py-12 sm:py-16 relative z-20">
        <div className="flex flex-col lg:flex-row gap-8 lg:gap-12">
          {/* Left Column */}
          <div className="lg:w-1/3 xl:w-1/2 lg:sticky lg:top-8 lg:self-start">
            <div className="mb-6 lg:mb-8">
              <div className="mb-3 lg:mb-4">
                <span className="text-base sm:text-lg font-medium text-gray-600 relative inline-block">
                  <span className="relative z-10">Key Features Of</span>
                </span>
              </div>

              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-4 lg:mb-6 leading-tight">
                AI Assistant for Smarter Workplaces
              </h2>

              <div className="bg-gradient-to-r from-blue-50 to-gray-50 rounded-xl p-5 sm:p-6 border border-gray-200 shadow-sm">
                <p className="text-sm sm:text-base text-gray-700 leading-relaxed">
                  Nerdy Buddy is an AI-powered assistant that helps employees find information, complete training, and stay productive – all while keeping your data secure.
                </p>
              </div>
            </div>
          </div>

          {/* Right Column - Features Grid */}
          <div className="lg:w-2/3 xl:w-1/2 h-[1000px] overflow-auto">
            <div className="grid grid-cols-1 gap-6 sm:gap-8">
              {features.map((feature, index) => (
                <div
                  key={feature.id}
                  className="group relative bg-white rounded-xl sm:rounded-2xl overflow-hidden border border-gray-200 hover:border-blue-300 transition-all duration-300 hover:shadow-xl"
                  data-wow-delay="ms"
                >
                  <a className="absolute inset-0 z-10" href="#"></a>

                  <div className="flex flex-col sm:flex-row items-start p-4 sm:p-5 md:p-6">
                    {/* Image Container */}
                    <div className="w-full sm:w-1/4 md:w-1/3 mb-4 sm:mb-0 sm:mr-4 md:mr-6">
                      <div className="relative overflow-hidden rounded-lg sm:rounded-xl">
                        <img
                          loading="lazy"
                          src={feature.image}
                          alt={feature.alt}
                          className="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-300"
                          width="263"
                          height="304"
                        />
                      </div>
                    </div>

                    {/* Content Container */}
                    <div className="w-full sm:w-3/4 md:w-2/3">
                      <h3 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-2 sm:mb-3 leading-tight">
                        {feature.title}
                      </h3>

                      <div className="w-10 sm:w-12 h-1 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full mb-3 sm:mb-4"></div>

                      <p className="text-sm sm:text-base text-gray-600 leading-relaxed pr-8 sm:pr-0">
                        {feature.description}
                      </p>

                      {/* Arrow Icon */}
                      <div className="absolute bottom-4 right-4 sm:bottom-6 sm:right-6 text-gray-800 group-hover:text-blue-600 transition-colors duration-300">
                        <ArrowIcon />
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIAssistantFeatures;